name: Integration

on:
  pull_request:
    branches:
    - main

jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          diagnostic-endpoint: ""
      - uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          diagnostic-endpoint: ""
          use-flakehub: false
      - uses: DeterminateSystems/flake-checker-action@v9
        with:
          send-statistics: false
          nixpkgs-keys: nixpkgs,unstable-nixpkgs
      - name: checks
        run: nix develop --command just check
      - name: build
        run: nix develop --command just build

